### ISSUE TITLE
Can you provide the config file about fine-tuning Stable Diffusion using LoRA?

### ISSUE THREAD

**Issue by caiwenchuan008** [KAIST-Visual-AI-Group/APAP#1]
I didn't find 'configs/lora_train/apap_3d.txt' in the repo.

**Comment by DveloperY0115** [comment]
Hi @caiwenchuan008,

Thank you for your interest in our work.
I have just pushed the config file to this repository. Could you fetch the update and check again?

Please let me know if you run into any issues.
