### ISSUE TITLE
User settings about control points

### ISSUE THREAD

**Issue by hhchen-create** [KAIST-Visual-AI-Group/APAP#2]
Hi, I am very interested in this work.
I am trying to use APAP to deform some meshes.
I would like to ask how do we select movable points, target positions, and anchor points? Is there any quick and convenient tool?

**Comment by DveloperY0115** [comment]
Hi @hhchen-create,

Thank you for your interest in our work!

I am sorry to say that our codebase does not support an interactive GUI for editing.

In our experiments, we specified vertices individually using [MeshLab](https://www.meshlab.net/), utilizing its feature to display vertex IDs and manually annotated target coordinates for individual handles.

**Comment by hhchen-create** [comment]
Hi, 

I see. Thank you for your quick response! 
Very nice work!
