### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by hhchen-create** [KAIST-Visual-AI-Group/APAP#3]
Hi,  I am trying to use APAP to deform some of my meshes.

After I trained Lora, set control points, and finally ran the deform part, I encountered that 

in PoissonSystem.py", line 109: 
return CholeskySolverD(self.n, self.inds[0,:], self.inds[1,:], self.vals, MatrixType.COO)
ValueError: Matrix is not positive definite!

So, are there any requirements for the input mesh?

**Comment by DveloperY0115** [comment]
Hi @hhchen-create,

Thank you for your interest in our work!

As we represent triangular meshes as Jacobian fields, we need to pre-factorize Laplacian matrices before SDS optimization.
To do so, the matrices should be positive definite for Cholesky decomposition, which may not be the case for meshes with, for instance, duplicate vertices/faces, isolated components, etc.

We preprocessed some meshes used in our experiments using the utility function defined [here](https://github.com/KAIST-Visual-AI-Group/APAP/blob/06f3d728e7da6ea2bc039981b5ad614e25f0180b/src/utils/geometry_utils.py#L555). It would be good to give it a shot.

Thank you.

**Comment by hhchen-create** [comment]
Hi, @DveloperY0115 

Thanks for your kind feedback and very useful suggestions.

It works for me now! 

Thank you.
